# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replay.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='replay.proto',
  package='team5002',
  syntax='proto3',
  serialized_pb=_b('\n\x0creplay.proto\x12\x08team5002\"P\n\x0c\x43ontrolState\x12\x14\n\x0c\x66orward_axis\x18\x01 \x01(\x01\x12\x17\n\x0fhorizontal_axis\x18\x02 \x01(\x01\x12\x11\n\tturn_axis\x18\x03 \x01(\x01\"b\n\x06Replay\x12%\n\x05state\x18\x01 \x03(\x0b\x32\x16.team5002.ControlState\x12\x18\n\x10replay_frequency\x18\x02 \x01(\x01\x12\x17\n\x0f\x62\x61ttery_voltage\x18\x03 \x01(\x01\x42)\n%org.usfirst.frc.team5002.robot.replayP\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTROLSTATE = _descriptor.Descriptor(
  name='ControlState',
  full_name='team5002.ControlState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='forward_axis', full_name='team5002.ControlState.forward_axis', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='horizontal_axis', full_name='team5002.ControlState.horizontal_axis', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turn_axis', full_name='team5002.ControlState.turn_axis', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=106,
)


_REPLAY = _descriptor.Descriptor(
  name='Replay',
  full_name='team5002.Replay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='team5002.Replay.state', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replay_frequency', full_name='team5002.Replay.replay_frequency', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery_voltage', full_name='team5002.Replay.battery_voltage', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=206,
)

_REPLAY.fields_by_name['state'].message_type = _CONTROLSTATE
DESCRIPTOR.message_types_by_name['ControlState'] = _CONTROLSTATE
DESCRIPTOR.message_types_by_name['Replay'] = _REPLAY

ControlState = _reflection.GeneratedProtocolMessageType('ControlState', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLSTATE,
  __module__ = 'replay_pb2'
  # @@protoc_insertion_point(class_scope:team5002.ControlState)
  ))
_sym_db.RegisterMessage(ControlState)

Replay = _reflection.GeneratedProtocolMessageType('Replay', (_message.Message,), dict(
  DESCRIPTOR = _REPLAY,
  __module__ = 'replay_pb2'
  # @@protoc_insertion_point(class_scope:team5002.Replay)
  ))
_sym_db.RegisterMessage(Replay)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n%org.usfirst.frc.team5002.robot.replayP\001'))
# @@protoc_insertion_point(module_scope)
