// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/usfirst/frc/team5002/robot/replay.proto

package org.usfirst.frc.team5002.robot.replay;

public interface ControlStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:team5002.ControlState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Forward / backward movement axis.
   * </pre>
   *
   * <code>optional double fwdAxis = 1;</code>
   */
  boolean hasFwdAxis();
  /**
   * <pre>
   * Forward / backward movement axis.
   * </pre>
   *
   * <code>optional double fwdAxis = 1;</code>
   */
  double getFwdAxis();

  /**
   * <pre>
   * Left / right strafing axis.
   * </pre>
   *
   * <code>optional double sideAxis = 2;</code>
   */
  boolean hasSideAxis();
  /**
   * <pre>
   * Left / right strafing axis.
   * </pre>
   *
   * <code>optional double sideAxis = 2;</code>
   */
  double getSideAxis();

  /**
   * <pre>
   * CW / CCW rotation axis.
   * </pre>
   *
   * <code>optional double turnAxis = 3;</code>
   */
  boolean hasTurnAxis();
  /**
   * <pre>
   * CW / CCW rotation axis.
   * </pre>
   *
   * <code>optional double turnAxis = 3;</code>
   */
  double getTurnAxis();
}
