// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/usfirst/frc/team5002/robot/replay.proto

package org.usfirst.frc.team5002.robot.replay;

public interface ControlStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:team5002.ControlState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional double forward_axis = 1;</code>
   */
  double getForwardAxis();

  /**
   * <code>optional double horizontal_axis = 2;</code>
   */
  double getHorizontalAxis();

  /**
   * <code>optional double turn_axis = 3;</code>
   */
  double getTurnAxis();
}
