// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: replay.proto

package org.usfirst.frc.team5002.robot.replay;

public final class ReplayOuterClass {
  private ReplayOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_team5002_ControlState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_team5002_ControlState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_team5002_Replay_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_team5002_Replay_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014replay.proto\022\010team5002\"P\n\014ControlState" +
      "\022\024\n\014forward_axis\030\001 \001(\001\022\027\n\017horizontal_axi" +
      "s\030\002 \001(\001\022\021\n\tturn_axis\030\003 \001(\001\"b\n\006Replay\022%\n\005" +
      "state\030\001 \003(\0132\026.team5002.ControlState\022\030\n\020r" +
      "eplay_frequency\030\002 \001(\001\022\027\n\017battery_voltage" +
      "\030\003 \001(\001B)\n%org.usfirst.frc.team5002.robot" +
      ".replayP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_team5002_ControlState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_team5002_ControlState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_team5002_ControlState_descriptor,
        new java.lang.String[] { "ForwardAxis", "HorizontalAxis", "TurnAxis", });
    internal_static_team5002_Replay_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_team5002_Replay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_team5002_Replay_descriptor,
        new java.lang.String[] { "State", "ReplayFrequency", "BatteryVoltage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
