// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/usfirst/frc/team5002/robot/replay.proto

package org.usfirst.frc.team5002.robot.replay;

public final class ReplayOuterClass {
  private ReplayOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_team5002_ControlState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_team5002_ControlState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_team5002_Replay_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_team5002_Replay_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+org/usfirst/frc/team5002/robot/replay." +
      "proto\022\010team5002\"C\n\014ControlState\022\017\n\007fwdAx" +
      "is\030\001 \001(\001\022\020\n\010sideAxis\030\002 \001(\001\022\020\n\010turnAxis\030\003" +
      " \001(\001\"m\n\006Replay\022&\n\006states\030\001 \003(\0132\026.team500" +
      "2.ControlState\022\033\n\017replayFrequency\030\002 \001(\001:" +
      "\00230\022\036\n\022replayBatteryLevel\030\003 \001(\001:\00212B)\n%o" +
      "rg.usfirst.frc.team5002.robot.replayP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_team5002_ControlState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_team5002_ControlState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_team5002_ControlState_descriptor,
        new java.lang.String[] { "FwdAxis", "SideAxis", "TurnAxis", });
    internal_static_team5002_Replay_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_team5002_Replay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_team5002_Replay_descriptor,
        new java.lang.String[] { "States", "ReplayFrequency", "ReplayBatteryLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
