// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/usfirst/frc/team5002/robot/replay.proto

package org.usfirst.frc.team5002.robot.replay;

public interface ReplayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:team5002.Replay)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .team5002.ControlState state = 1;</code>
   */
  java.util.List<org.usfirst.frc.team5002.robot.replay.ControlState> 
      getStateList();
  /**
   * <code>repeated .team5002.ControlState state = 1;</code>
   */
  org.usfirst.frc.team5002.robot.replay.ControlState getState(int index);
  /**
   * <code>repeated .team5002.ControlState state = 1;</code>
   */
  int getStateCount();
  /**
   * <code>repeated .team5002.ControlState state = 1;</code>
   */
  java.util.List<? extends org.usfirst.frc.team5002.robot.replay.ControlStateOrBuilder> 
      getStateOrBuilderList();
  /**
   * <code>repeated .team5002.ControlState state = 1;</code>
   */
  org.usfirst.frc.team5002.robot.replay.ControlStateOrBuilder getStateOrBuilder(
      int index);

  /**
   * <code>optional double replay_frequency = 2;</code>
   */
  double getReplayFrequency();

  /**
   * <code>optional double battery_voltage = 3;</code>
   */
  double getBatteryVoltage();
}
