// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/usfirst/frc/team5002/robot/replay.proto

package org.usfirst.frc.team5002.robot.replay;

/**
 * Protobuf type {@code team5002.Replay}
 */
public  final class Replay extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:team5002.Replay)
    ReplayOrBuilder {
  // Use Replay.newBuilder() to construct.
  private Replay(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Replay() {
    state_ = java.util.Collections.emptyList();
    replayFrequency_ = 0D;
    batteryVoltage_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Replay(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              state_ = new java.util.ArrayList<org.usfirst.frc.team5002.robot.replay.ControlState>();
              mutable_bitField0_ |= 0x00000001;
            }
            state_.add(
                input.readMessage(org.usfirst.frc.team5002.robot.replay.ControlState.parser(), extensionRegistry));
            break;
          }
          case 17: {

            replayFrequency_ = input.readDouble();
            break;
          }
          case 25: {

            batteryVoltage_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        state_ = java.util.Collections.unmodifiableList(state_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.usfirst.frc.team5002.robot.replay.ReplayOuterClass.internal_static_team5002_Replay_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.usfirst.frc.team5002.robot.replay.ReplayOuterClass.internal_static_team5002_Replay_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.usfirst.frc.team5002.robot.replay.Replay.class, org.usfirst.frc.team5002.robot.replay.Replay.Builder.class);
  }

  private int bitField0_;
  public static final int STATE_FIELD_NUMBER = 1;
  private java.util.List<org.usfirst.frc.team5002.robot.replay.ControlState> state_;
  /**
   * <pre>
   * Actual replay data.
   * </pre>
   *
   * <code>repeated .team5002.ControlState state = 1;</code>
   */
  public java.util.List<org.usfirst.frc.team5002.robot.replay.ControlState> getStateList() {
    return state_;
  }
  /**
   * <pre>
   * Actual replay data.
   * </pre>
   *
   * <code>repeated .team5002.ControlState state = 1;</code>
   */
  public java.util.List<? extends org.usfirst.frc.team5002.robot.replay.ControlStateOrBuilder> 
      getStateOrBuilderList() {
    return state_;
  }
  /**
   * <pre>
   * Actual replay data.
   * </pre>
   *
   * <code>repeated .team5002.ControlState state = 1;</code>
   */
  public int getStateCount() {
    return state_.size();
  }
  /**
   * <pre>
   * Actual replay data.
   * </pre>
   *
   * <code>repeated .team5002.ControlState state = 1;</code>
   */
  public org.usfirst.frc.team5002.robot.replay.ControlState getState(int index) {
    return state_.get(index);
  }
  /**
   * <pre>
   * Actual replay data.
   * </pre>
   *
   * <code>repeated .team5002.ControlState state = 1;</code>
   */
  public org.usfirst.frc.team5002.robot.replay.ControlStateOrBuilder getStateOrBuilder(
      int index) {
    return state_.get(index);
  }

  public static final int REPLAY_FREQUENCY_FIELD_NUMBER = 2;
  private double replayFrequency_;
  /**
   * <pre>
   * Frequency of state updates, in Hz
   * </pre>
   *
   * <code>optional double replay_frequency = 2;</code>
   */
  public double getReplayFrequency() {
    return replayFrequency_;
  }

  public static final int BATTERY_VOLTAGE_FIELD_NUMBER = 3;
  private double batteryVoltage_;
  /**
   * <pre>
   * Battery level at the beginning of the recording session, in volts.
   * </pre>
   *
   * <code>optional double battery_voltage = 3;</code>
   */
  public double getBatteryVoltage() {
    return batteryVoltage_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < state_.size(); i++) {
      output.writeMessage(1, state_.get(i));
    }
    if (replayFrequency_ != 0D) {
      output.writeDouble(2, replayFrequency_);
    }
    if (batteryVoltage_ != 0D) {
      output.writeDouble(3, batteryVoltage_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < state_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, state_.get(i));
    }
    if (replayFrequency_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, replayFrequency_);
    }
    if (batteryVoltage_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, batteryVoltage_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.usfirst.frc.team5002.robot.replay.Replay)) {
      return super.equals(obj);
    }
    org.usfirst.frc.team5002.robot.replay.Replay other = (org.usfirst.frc.team5002.robot.replay.Replay) obj;

    boolean result = true;
    result = result && getStateList()
        .equals(other.getStateList());
    result = result && (
        java.lang.Double.doubleToLongBits(getReplayFrequency())
        == java.lang.Double.doubleToLongBits(
            other.getReplayFrequency()));
    result = result && (
        java.lang.Double.doubleToLongBits(getBatteryVoltage())
        == java.lang.Double.doubleToLongBits(
            other.getBatteryVoltage()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getStateCount() > 0) {
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getStateList().hashCode();
    }
    hash = (37 * hash) + REPLAY_FREQUENCY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getReplayFrequency()));
    hash = (37 * hash) + BATTERY_VOLTAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBatteryVoltage()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.usfirst.frc.team5002.robot.replay.Replay parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.usfirst.frc.team5002.robot.replay.Replay parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.usfirst.frc.team5002.robot.replay.Replay parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.usfirst.frc.team5002.robot.replay.Replay parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.usfirst.frc.team5002.robot.replay.Replay parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.usfirst.frc.team5002.robot.replay.Replay parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.usfirst.frc.team5002.robot.replay.Replay parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.usfirst.frc.team5002.robot.replay.Replay parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.usfirst.frc.team5002.robot.replay.Replay parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.usfirst.frc.team5002.robot.replay.Replay parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.usfirst.frc.team5002.robot.replay.Replay prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code team5002.Replay}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:team5002.Replay)
      org.usfirst.frc.team5002.robot.replay.ReplayOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.usfirst.frc.team5002.robot.replay.ReplayOuterClass.internal_static_team5002_Replay_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.usfirst.frc.team5002.robot.replay.ReplayOuterClass.internal_static_team5002_Replay_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.usfirst.frc.team5002.robot.replay.Replay.class, org.usfirst.frc.team5002.robot.replay.Replay.Builder.class);
    }

    // Construct using org.usfirst.frc.team5002.robot.replay.Replay.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStateFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (stateBuilder_ == null) {
        state_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        stateBuilder_.clear();
      }
      replayFrequency_ = 0D;

      batteryVoltage_ = 0D;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.usfirst.frc.team5002.robot.replay.ReplayOuterClass.internal_static_team5002_Replay_descriptor;
    }

    public org.usfirst.frc.team5002.robot.replay.Replay getDefaultInstanceForType() {
      return org.usfirst.frc.team5002.robot.replay.Replay.getDefaultInstance();
    }

    public org.usfirst.frc.team5002.robot.replay.Replay build() {
      org.usfirst.frc.team5002.robot.replay.Replay result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.usfirst.frc.team5002.robot.replay.Replay buildPartial() {
      org.usfirst.frc.team5002.robot.replay.Replay result = new org.usfirst.frc.team5002.robot.replay.Replay(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (stateBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          state_ = java.util.Collections.unmodifiableList(state_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.state_ = state_;
      } else {
        result.state_ = stateBuilder_.build();
      }
      result.replayFrequency_ = replayFrequency_;
      result.batteryVoltage_ = batteryVoltage_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.usfirst.frc.team5002.robot.replay.Replay) {
        return mergeFrom((org.usfirst.frc.team5002.robot.replay.Replay)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.usfirst.frc.team5002.robot.replay.Replay other) {
      if (other == org.usfirst.frc.team5002.robot.replay.Replay.getDefaultInstance()) return this;
      if (stateBuilder_ == null) {
        if (!other.state_.isEmpty()) {
          if (state_.isEmpty()) {
            state_ = other.state_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStateIsMutable();
            state_.addAll(other.state_);
          }
          onChanged();
        }
      } else {
        if (!other.state_.isEmpty()) {
          if (stateBuilder_.isEmpty()) {
            stateBuilder_.dispose();
            stateBuilder_ = null;
            state_ = other.state_;
            bitField0_ = (bitField0_ & ~0x00000001);
            stateBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStateFieldBuilder() : null;
          } else {
            stateBuilder_.addAllMessages(other.state_);
          }
        }
      }
      if (other.getReplayFrequency() != 0D) {
        setReplayFrequency(other.getReplayFrequency());
      }
      if (other.getBatteryVoltage() != 0D) {
        setBatteryVoltage(other.getBatteryVoltage());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.usfirst.frc.team5002.robot.replay.Replay parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.usfirst.frc.team5002.robot.replay.Replay) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.usfirst.frc.team5002.robot.replay.ControlState> state_ =
      java.util.Collections.emptyList();
    private void ensureStateIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        state_ = new java.util.ArrayList<org.usfirst.frc.team5002.robot.replay.ControlState>(state_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.usfirst.frc.team5002.robot.replay.ControlState, org.usfirst.frc.team5002.robot.replay.ControlState.Builder, org.usfirst.frc.team5002.robot.replay.ControlStateOrBuilder> stateBuilder_;

    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public java.util.List<org.usfirst.frc.team5002.robot.replay.ControlState> getStateList() {
      if (stateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(state_);
      } else {
        return stateBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public int getStateCount() {
      if (stateBuilder_ == null) {
        return state_.size();
      } else {
        return stateBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public org.usfirst.frc.team5002.robot.replay.ControlState getState(int index) {
      if (stateBuilder_ == null) {
        return state_.get(index);
      } else {
        return stateBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public Builder setState(
        int index, org.usfirst.frc.team5002.robot.replay.ControlState value) {
      if (stateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStateIsMutable();
        state_.set(index, value);
        onChanged();
      } else {
        stateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public Builder setState(
        int index, org.usfirst.frc.team5002.robot.replay.ControlState.Builder builderForValue) {
      if (stateBuilder_ == null) {
        ensureStateIsMutable();
        state_.set(index, builderForValue.build());
        onChanged();
      } else {
        stateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public Builder addState(org.usfirst.frc.team5002.robot.replay.ControlState value) {
      if (stateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStateIsMutable();
        state_.add(value);
        onChanged();
      } else {
        stateBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public Builder addState(
        int index, org.usfirst.frc.team5002.robot.replay.ControlState value) {
      if (stateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStateIsMutable();
        state_.add(index, value);
        onChanged();
      } else {
        stateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public Builder addState(
        org.usfirst.frc.team5002.robot.replay.ControlState.Builder builderForValue) {
      if (stateBuilder_ == null) {
        ensureStateIsMutable();
        state_.add(builderForValue.build());
        onChanged();
      } else {
        stateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public Builder addState(
        int index, org.usfirst.frc.team5002.robot.replay.ControlState.Builder builderForValue) {
      if (stateBuilder_ == null) {
        ensureStateIsMutable();
        state_.add(index, builderForValue.build());
        onChanged();
      } else {
        stateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public Builder addAllState(
        java.lang.Iterable<? extends org.usfirst.frc.team5002.robot.replay.ControlState> values) {
      if (stateBuilder_ == null) {
        ensureStateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, state_);
        onChanged();
      } else {
        stateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public Builder clearState() {
      if (stateBuilder_ == null) {
        state_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        stateBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public Builder removeState(int index) {
      if (stateBuilder_ == null) {
        ensureStateIsMutable();
        state_.remove(index);
        onChanged();
      } else {
        stateBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public org.usfirst.frc.team5002.robot.replay.ControlState.Builder getStateBuilder(
        int index) {
      return getStateFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public org.usfirst.frc.team5002.robot.replay.ControlStateOrBuilder getStateOrBuilder(
        int index) {
      if (stateBuilder_ == null) {
        return state_.get(index);  } else {
        return stateBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public java.util.List<? extends org.usfirst.frc.team5002.robot.replay.ControlStateOrBuilder> 
         getStateOrBuilderList() {
      if (stateBuilder_ != null) {
        return stateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(state_);
      }
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public org.usfirst.frc.team5002.robot.replay.ControlState.Builder addStateBuilder() {
      return getStateFieldBuilder().addBuilder(
          org.usfirst.frc.team5002.robot.replay.ControlState.getDefaultInstance());
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public org.usfirst.frc.team5002.robot.replay.ControlState.Builder addStateBuilder(
        int index) {
      return getStateFieldBuilder().addBuilder(
          index, org.usfirst.frc.team5002.robot.replay.ControlState.getDefaultInstance());
    }
    /**
     * <pre>
     * Actual replay data.
     * </pre>
     *
     * <code>repeated .team5002.ControlState state = 1;</code>
     */
    public java.util.List<org.usfirst.frc.team5002.robot.replay.ControlState.Builder> 
         getStateBuilderList() {
      return getStateFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.usfirst.frc.team5002.robot.replay.ControlState, org.usfirst.frc.team5002.robot.replay.ControlState.Builder, org.usfirst.frc.team5002.robot.replay.ControlStateOrBuilder> 
        getStateFieldBuilder() {
      if (stateBuilder_ == null) {
        stateBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.usfirst.frc.team5002.robot.replay.ControlState, org.usfirst.frc.team5002.robot.replay.ControlState.Builder, org.usfirst.frc.team5002.robot.replay.ControlStateOrBuilder>(
                state_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        state_ = null;
      }
      return stateBuilder_;
    }

    private double replayFrequency_ ;
    /**
     * <pre>
     * Frequency of state updates, in Hz
     * </pre>
     *
     * <code>optional double replay_frequency = 2;</code>
     */
    public double getReplayFrequency() {
      return replayFrequency_;
    }
    /**
     * <pre>
     * Frequency of state updates, in Hz
     * </pre>
     *
     * <code>optional double replay_frequency = 2;</code>
     */
    public Builder setReplayFrequency(double value) {
      
      replayFrequency_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Frequency of state updates, in Hz
     * </pre>
     *
     * <code>optional double replay_frequency = 2;</code>
     */
    public Builder clearReplayFrequency() {
      
      replayFrequency_ = 0D;
      onChanged();
      return this;
    }

    private double batteryVoltage_ ;
    /**
     * <pre>
     * Battery level at the beginning of the recording session, in volts.
     * </pre>
     *
     * <code>optional double battery_voltage = 3;</code>
     */
    public double getBatteryVoltage() {
      return batteryVoltage_;
    }
    /**
     * <pre>
     * Battery level at the beginning of the recording session, in volts.
     * </pre>
     *
     * <code>optional double battery_voltage = 3;</code>
     */
    public Builder setBatteryVoltage(double value) {
      
      batteryVoltage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Battery level at the beginning of the recording session, in volts.
     * </pre>
     *
     * <code>optional double battery_voltage = 3;</code>
     */
    public Builder clearBatteryVoltage() {
      
      batteryVoltage_ = 0D;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:team5002.Replay)
  }

  // @@protoc_insertion_point(class_scope:team5002.Replay)
  private static final org.usfirst.frc.team5002.robot.replay.Replay DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.usfirst.frc.team5002.robot.replay.Replay();
  }

  public static org.usfirst.frc.team5002.robot.replay.Replay getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Replay>
      PARSER = new com.google.protobuf.AbstractParser<Replay>() {
    public Replay parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Replay(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Replay> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Replay> getParserForType() {
    return PARSER;
  }

  public org.usfirst.frc.team5002.robot.replay.Replay getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

